apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods-rolebinding
  namespace: default
subjects:
- kind: ServiceAccount
  name: admin
  namespace: default
roleRef:
  kind: Role
  name: admin-role
  apiGroup: rbac.authorization.k8s.io